import {useEffect,useState} from 'react'
import {api,write,setCsrf,errorMessage} from './api'
import type {Meeting,MeetingSummary,MeetingInput,User,Mutation} from './types'
import {TranscriptForm} from './TranscriptForm'
import {ProposalPanel} from './ProposalPanel'
import {MinutesPanel} from './MinutesPanel'
import {AuditPanel} from './AuditPanel'
import {EvaluationPanel} from './EvaluationPanel'
import {AdvicePanel} from './AdvicePanel'

export default function App(){
 const [user,setUser]=useState<User|null>(null);const [mode,setMode]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [meetings,setMeetings]=useState<MeetingSummary[]>([]);const [meeting,setMeeting]=useState<Meeting|null>(null);const [page,setPage]=useState<'workspace'|'new'|'audit'|'evaluation'>('workspace');const [query,setQuery]=useState('');const [source,setSource]=useState('');const [releases,setReleases]=useState<{revision:number;approved_by:string;approved_at:string}[]>([]);const [release,setRelease]=useState('')
 const canEdit=!!user?.roles.some(r=>['admin','reviewer'].includes(r))
 async function list(){setMeetings(await api<MeetingSummary[]>('/meetings'))}
 async function open(id:string){setError('');try{const [m,r]=await Promise.all([api<Meeting>('/meetings/'+id),api<typeof releases>('/meetings/'+id+'/releases')]);setMeeting(m);setReleases(r);setRelease('');setSource('');setPage('workspace')}catch(e){setError(errorMessage(e))}}
 useEffect(()=>{let alive=true;(async()=>{try{const m=await api<{mode:string}>('/auth/mode');if(alive)setMode(m.mode);try{const u=await api<User>('/auth/me');if(alive){setCsrf(u.csrf_token);setUser(u);await list()}}catch{/* No session is a normal login state. */}}catch(e){if(alive)setError(errorMessage(e))}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[])
 async function login(identity:string){setBusy(true);setError('');try{const u=await write<User>('/auth/demo?identity='+identity,{});setCsrf(u.csrf_token);setUser(u);await list()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function logout(){setBusy(true);setError('');try{await write('/auth/logout',{});setCsrf('');setUser(null);setMeeting(null);setMeetings([])}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function create(input:MeetingInput){setBusy(true);setError('');try{const m=await write<Meeting>('/meetings',input);await list();await open(m.id)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const mutate:Mutation=async(path,data,method='POST')=>{if(!meeting)return false;setBusy(true);setError('');try{await write('/meetings/'+meeting.id+path,{...data,revision:meeting.revision},method);await list();await open(meeting.id);return true}catch(e){setError(errorMessage(e));return false}finally{setBusy(false)}}
 function inspect(id:string){setSource(id);requestAnimationFrame(()=>document.getElementById('source-'+id)?.scrollIntoView({behavior:'smooth',block:'nearest'}))}
 async function remove(){if(!meeting||!confirm('Delete this meeting and its approved snapshots? Export any records you need first. Audit events remain.'))return;setBusy(true);try{await write('/meetings/'+meeting.id,{revision:meeting.revision},'DELETE');setMeeting(null);await list()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const filtered=meetings.filter(m=>m.title.toLowerCase().includes(query.toLowerCase()))
 return <><header><a className="brand" href="/">M<span>Meeting Minutes</span></a><span className="brand-note">Alan Vo · source-backed meeting records</span>{user&&<div className="account"><span>{user.username}</span><button className="secondary" disabled={busy} onClick={()=>void logout()}>Sign out</button></div>}</header>
 {error&&<div role="alert" className="error banner">{error}<button className="text-button" onClick={()=>setError('')}>Dismiss</button>{meeting&&<button className="text-button" onClick={()=>void open(meeting.id)}>Reload meeting</button>}</div>}
 {loading?<main className="login"><h1>Loading workspace…</h1></main>:!user?<main className="login"><p className="eyebrow">FROM CONVERSATION TO FOLLOW-THROUGH</p><h1>Minutes you can trace.<br/>Actions you can track.</h1><p>Review transcript citations, confirm decisions and preserve an approved record. Everyone can see where each item came from.</p><section className="panel"><h2>Sign in</h2>{mode==='demo'?<><p>Local demo personas. Use Analyst to prepare minutes and Reviewer to approve them independently.</p><div className="actions">{['analyst','reviewer','admin'].map(i=><button key={i} disabled={busy} onClick={()=>void login(i)}>Continue as {i}</button>)}</div></>:<><p>Use your organization’s identity provider.</p><a className="button" href="/api/auth/login">Continue with SSO</a></>}</section></main>:<div className="layout"><aside className="sidebar"><button disabled={busy||!canEdit} onClick={()=>{setPage('new');setMeeting(null)}}>+ New meeting</button><nav>{(['workspace','evaluation','audit'] as const).map(p=><button className={'nav-link '+(page===p?'active':'')} key={p} onClick={()=>setPage(p)}>{p==='workspace'?'Meetings':p==='evaluation'?'Extraction diagnostic':'Audit history'}</button>)}</nav><label className="search">Find a meeting<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles"/></label><div className="meeting-list">{filtered.map(m=><button className={'meeting-link '+(meeting?.id===m.id?'selected':'')} key={m.id} onClick={()=>void open(m.id)}><strong>{m.title}</strong><span>{m.meeting_date} · {m.status}</span></button>)}</div><p className="muted">{meetings.length} / 200 meetings<br/>One shared authenticated workspace</p></aside><main className="workspace">
 {page==='new'?<TranscriptForm onCreate={create} busy={busy}/>:page==='audit'?<AuditPanel/>:page==='evaluation'?<EvaluationPanel/>:!meeting?<section className="panel welcome"><p className="eyebrow">YOUR MEETING WORKSPACE</p><h1>Keep the source beside the decision.</h1><p>Select a meeting or create a draft from a text transcript. Rule-based extraction works offline, without any API key.</p><ol><li>Import a transcript with its date and participant roster.</li><li>Review candidates and attach exact source quotes.</li><li>Get independent approval, then track action status and export the record.</li></ol><button disabled={!canEdit} onClick={()=>setPage('new')}>Create your first draft</button></section>:<>
 <section className="meeting-heading"><p className="eyebrow">{meeting.kind.replaceAll('_',' ')} · {meeting.meeting_date}</p><h1>{meeting.title}</h1><p>{meeting.participants.join(' · ')}</p><div className="actions"><span className="badge">{meeting.status} · revision {meeting.revision}</span><button className="text-button" disabled={busy} onClick={()=>void open(meeting.id)}>Refresh</button>{user.roles.includes('admin')&&<button className="text-button danger" disabled={busy} onClick={()=>void remove()}>Delete meeting</button>}</div></section>
 <div className="metrics"><div><strong>{meeting.digest.counts.action}</strong><span>Actions</span></div><div><strong>{meeting.digest.counts.decision}</strong><span>Decisions</span></div><div><strong>{meeting.digest.unassigned_actions}</strong><span>Unassigned</span></div><div><strong>{meeting.digest.done_actions}</strong><span>Completed</span></div></div>
 <div className="review-grid"><div><ProposalPanel meeting={meeting} mutate={mutate} busy={busy} editable={canEdit&&meeting.status==='draft'} onSource={inspect}/><MinutesPanel key={meeting.id} meeting={meeting} mutate={mutate} busy={busy} user={user} onSource={inspect}/><AdvicePanel key={meeting.id+'-'+meeting.revision} meeting={meeting} mutate={mutate} busy={busy} editable={canEdit&&meeting.status==='draft'}/></div><section className="panel transcript"><p className="eyebrow">ORIGINAL TRANSCRIPT</p><h2>Source record</h2><p className="muted">{meeting.document.turns.length} turns · Text is immutable after import.</p><div className="transcript-scroll">{meeting.document.turns.map(t=><article id={'source-'+t.id} key={t.id} className={'turn '+(source===t.id?'highlight':'')}><strong>{t.id} · {t.speaker??t.raw_speaker??'Unlabeled'}</strong><small>{t.timestamp??''} · line {t.line}</small><p>{t.text}</p></article>)}</div><details><summary>Source fingerprint</summary><code>{meeting.document.sha256}</code></details></section></div>
 <section className="panel"><p className="eyebrow">PORTABLE RECORDS</p><h2>Export minutes</h2><label>Record version<select aria-label="Record version" value={release} onChange={e=>setRelease(e.target.value)}><option value="">Current working record · revision {meeting.revision}</option>{releases.map(r=><option key={r.revision} value={r.revision}>Approved revision {r.revision} · {r.approved_by}</option>)}</select></label><div className="actions">{['markdown','json','csv','slack','ics'].map(f=><a className="button secondary" key={f} href={'/api/meetings/'+meeting.id+'/export/'+f+(release?'?release='+release:'')}>{f.toUpperCase()}</a>)}</div><p className="muted">Calendar files contain dated, unfinished actions as all-day events. Slack text is downloaded, never posted. Exported records can contain confidential transcript excerpts.</p></section><AuditPanel key={meeting.id+'-'+meeting.revision} meetingId={meeting.id}/>
 </>}
 </main></div>}<footer>Alan Vo · <a href="mailto:alanvo@gmail.com">alanvo@gmail.com</a> · Meeting Minutes · <a href="https://github.com/ALANDVO/meeting-minutes-alan-vo">Source</a></footer></>
}
